
# INCLUDE(FindLua)
# IF(NOT LUA_FOUND)
	SET(LUA_LIBRARIES lua;m;${CMAKE_DL_LIBS})
	SET(LUA_VERSION_PATCH 1)
	SET(LUA_VERSION_MINOR 3)
	SET(LUA_VERSION_MAJOR 5)
	SET(LUA_VERSION_STRING "${LUA_VERSION_MAJOR}.${LUA_VERSION_MINOR}.${LUA_VERSION_PATCH}")
	SET(LUA_INCLUDE_DIR "lua")

	ADD_DEFINITIONS(-DLUA_COMPAT_5_2)

